#!/bin/bash

source env/bin/activate
pip install -r requirements.txt
export BATTLEDICE_SECRET='ASFDFSF$%0gfni'
export FLASK_APP=$(pwd)/autoapp.py
export FLASK_DEBUG=1
bower install
pip install -r requirements/dev.txt
flask run
